apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
spec:
  containers:
    - name: demo-container-1
      image: "ubuntu:20.04"
      command: ["sleep"]
      args: ["infinity"]
      resources:
        limits:
          "nvidia.com/gpu": 1
          "openshift.io/roce": 1
